---
- name: set zfs facts
  set_fact:
    jails_ds:       "{{ jails_zpool ~ jails_mount }}" # main dataset
    jails_dss:      "{{ jails_zpool ~ jails_mount }}/" # a convenient trailing slash
    jails_template: "{{ jails_zpool ~ jails_mount ~ '/templates/' ~ [jails_target, jails_machine, jails_arch] | join('-') }}"
  tags: jails, facts

- name: create main dataset
  community.general.zfs:
    name: "{{ jails_ds }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ jails_mount }}"
      readonly: off
      atime: off
  tags: jails, zfs

- name: create intermediary datasets
  community.general.zfs:
    name: "{{ jails_dss ~ item }}"
    state: present
    extra_zfs_properties:
      readonly: off
      canmount: off
  loop:
    - downloads
    - templates
    - instances
  tags: jails, zfs

- name: create template dataset
  community.general.zfs:
    name: "{{ jails_template }}"
    state: present
    extra_zfs_properties:
      readonly: off
  loop:
    - downloads
    - templates
  tags: jails, zfs

- name: set permissions
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    owner: root
    group: wheel
    mode: '0770'
  loop:
    - "{{ jails_mount }}"
    - "{{ jails_mount }}/downloads"
    - "{{ jails_mount }}/templates"
    - "{{ jails_mount }}/instances"
  tags: jails, zfs

