---
- name: update fact cache
  ansible.builtin.setup:
  delegate_to: '{{ instance_name }}'
  delegate_facts: true
  tags: instance, facts
  loop: '{{ groups[instance_groups] | default([]) }}'
  when: instance_groups is defined

- name: dump ansible env
  debug:
    msg: |
      {
        "env": {{ environment | to_nice_json }},
        "groups": {{ group_names| default([])  | to_nice_json }},
        "group_vars": {{ groups | to_nice_json }},
        "host_vars": {{ hostvars[inventory_hostname] | to_nice_json }}
      }
    verbosity: 2
  tags: instance, setup, debug
