---
- name: update fact cache for instance
  ansible.builtin.setup:
  delegate_to: '{{ instance_name }}'
  delegate_facts: true
  tags: inventory

- name: update fact cache with instance groups
  ansible.builtin.setup:
  delegate_to: '{{ item }}'
  delegate_facts: true
  ignore_unreachable: true
  ignore_errors: true
  loop: >-
    {{
      (instance_groups if instance_groups is sequence and instance_groups is not string
       else instance_groups.split(',') | map('trim') | list)
      | map('extract', groups)
      | flatten
      | unique
      | list
    }}
  when: instance_groups is defined and instance_groups | length > 0
  tags: inventory
