---
- name: set instance facts
  set_fact:
    # helper for subsequent facts
    instance_path: '{{ "/instances/" ~ [jails_target, jails_machine, jails_arch] | join("-") ~ "/" ~ instance.name }}'
    # zfs origin template for clone
    jails_template: '{{ jails_zpool ~ jails_mount ~ "/templates/" ~ [jails_target, jails_machine, jails_arch] | join("-") }}'
  tags: jails, facts

- name: set instance facts
  set_fact:
    # per-instance
    instance_zfs: '{{ jails_zpool ~ jails_mount ~ instance_path }}'
    instance_dir: '{{ jails_mount ~ instance_path }}'
    instance_etc: '{{ jails_mount ~ instance_path ~ "/etc" }}'
    instance_facts: '{{ jails_mount ~ instance_path ~ "/usr/local/etc/ansible/facts.d" }}'
    instance_name: '{{ instance.name ~ "@" ~ ansible_ssh_host }}'
    instance_hostname: '{{ instance.hostname | default(instance.name) }}'
    instance_packages: '{{ instance.packages | default([]) | join(" ") }}'
    instance_daemons: '{{ instance.daemons | default([]) }}'
    # handle both single items and arrays for IP addresses
    # if a single item is provided, convert it to a list
    instance_ip4_addrs: "{{ [instance.ip4_addr] if (instance.ip4_addr is defined and instance.ip4_addr is string) else
                           (instance.ip4_addrs | default(['127.0.0.1/32'])) }}"
    instance_ip6_addrs: "{{ [instance.ip6_addr] if (instance.ip6_addr is defined and instance.ip6_addr is string) else
                           (instance.ip6_addrs | default(['::1/128'])) }}"
    # to be templated out by either role or custom template
    instance_cfg: '/etc/jail.conf.d/{{ instance.name }}.conf'
  tags: jails, facts

- name: clone per-instance zfs dataset
  community.general.zfs:
    name: '{{ instance_zfs }}'
    origin: '{{ instance.template | default(jails_template ~ "@ready") }}'
    state: present
    extra_zfs_properties:
      readonly: off
  tags: jails, zfs

- name: set hostname in rc.conf
  lineinfile:
    path: '{{ instance_etc }}/rc.conf'
    line: 'hostname={{ instance_hostname }}'
    regexp: '^hostname='
    create: true
  tags: jails, hostname

- name: set resolv.conf
  copy:
    content: "{{ jails_resolv_conf }}"
    dest: "{{ instance_etc }}/resolv.conf"
    mode: 0644
    owner: root
    group: wheel
  tags: jails, resolv

- name: enable any user-requested daemons
  lineinfile:
    dest: '{{ instance_etc }}/rc.conf'
    line: '{{ item }}_enable=YES'
    regexp: '^{{ item }}_enable='
  loop: '{{ instance_daemons }}'
  when: instance.daemons is defined
  tags: jails, template, services

- name: install instance packages
  ansible.builtin.command:
    cmd: >
      /usr/bin/env
        ASSUME_ALWAYS_YES=yes
        AUTOCLEAN=yes
      /usr/local/sbin/pkg
          --chroot {{ instance_dir }}
          install -r {{ jails_repo }}
          -y {{ instance_packages }}
  when: instance.packages is defined
  no_log: "{{ ansible_verbosity < 2 }}"
  tags: jails, template, python, packages


- name: create per-instance jail.conf
  template:
    src: '{{ instance.jail_conf | default(jails_instance_conf) }}'
    dest: '{{ instance_cfg }}'
    mode: 0440
  tags: jails, daemon

- name: verify jailed zfs dataset exists
  ansible.builtin.command:
    cmd: >
      /sbin/zfs list -Ho name {{ instance.zfs }}
  register: zfs_check
  failed_when: zfs_check.rc != 0
  changed_when: false
  when: instance.zfs is defined
  tags: jails, template, start

- name: start jail {{ instance.name }}
  ansible.builtin.command:
    cmd: >
      service jail start {{ instance.name }}
  tags: jails, template, start

- name: add jail to inventory
  ansible.builtin.add_host:
    name: '{{ instance_name }}'
    hostname: '{{ instance_hostname }}'
    groups: '{{ instance.groups | default([]) }}'
    ansible_connection: 'sshjail'
    ansible_ssh_port: '{{ansible_ssh_port | default("22") }}'
    ansible_python_interpreter: '/usr/local/bin/python3'

- name: add convenience softlink to jail
  file:
    src: '{{ instance_dir }}'
    dest: '/jails/tags/{{ instance.name }}'
    state: link
    force: true

- name: inject instance facts
  copy:
    content: |
     {{ lookup('template', 'instance.facts.j2') | from_yaml | to_nice_json }}
    dest: '{{ instance_facts }}/instance.fact'
    mode: 0644
    owner: root
    group: wheel
  tags: jails, instance, facts

- name: run inventory with root & python
  ansible.builtin.setup:
    fact_path: '{{ instance_facts }}'
  delegate_to: '{{ instance_name }}'
  delegate_facts: true
  tags: inventory

- name: dump custom facts from inventory
  debug:
    var: ansible_local
    verbosity: 2
  delegate_to: '{{ instance_name }}'
  delegate_facts: true
  tags: debug, inventory

- name: run final snapshot
  ansible.builtin.command:
    cmd: >
      /sbin/zfs snapshot {{ instance_zfs }}@ready
    creates: '{{ instance_dir }}/.zfs/snapshot/ready'
  tags: instance, template, zfs
