---
- name: Converge - template only
  hosts: localhost
  become: true
  vars:
    jails_zpool: zroot
    jails_mount: /jails_test
    jails_patch_template: false
    jails_verify_template: false
    jails_list: []
    # template hooks: extra packages and a custom role before @ready
    jails_default_packages:
      - sysutils/tree
    jails_template_role: template_marker
    jails_repo: molecule
    jails_repo_config: |
      molecule: {
        # CURRENT and STABLE have no quarterly branch
        url: "https://pkg.FreeBSD.org/${ABI}/{{ 'quarterly' if ansible_facts['distribution_release'] is search('-RELEASE') else 'latest' }}",
        mirror_type: "srv",
        signature_type: "fingerprints",
        fingerprints: "/usr/share/keys/pkg",
        enabled: yes
      }
  roles:
    - role: ansible-jails
